basic:
    images_path: 'D:\Dev\Projects\rotcool\tools\slideshow\Test'
    url: 'http://127.0.0.1'
    port: 5000

anime:
    duration: 3000
    anime_duration: 300
    background_image: './bg.png'
    show_displaying_info: true
