name: Releaser

on:
  release:
    tags: [created]

jobs:
  releaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          project_path: ./server
          binary_name: server
          goversion: 1.22
          extra_files: index.html style.css config.yaml README.md
